version: '3'

services:
  fidelyn-app:    
    image: nginx:alpine
    container_name: fidelyn-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: mysql-fidelyn
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fidelyn
      MYSQL_DATABASE: fidelyn
      MYSQL_USER: fidelyn
      MYSQL_PASSWORD: fidelyn
  
  php:
    build: .
    container_name: php-fidelyn
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"